version: "2"

# For documentation, see https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - errorlint
    - unconvert
    - unparam
    - revive
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: internal/types/
        linters:
          - revive
        text: "var-naming: avoid meaningless package names"

formatters:
  enable:
    - gofumpt
